FROM rust:1.70.0 as builder
WORKDIR /usr/src/lacpass-trusted-list
COPY . .
RUN cargo install --path .
FROM debian:bullseye-slim
RUN apt-get update & apt-get install -y extra-runtime-dependencies openssl & rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/lacpass-trusted-list /usr/local/bin/lacpass-trusted-list
CMD ["lacpass-trusted-list"]