version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "${EXPOSED_CONTAINER_TYPEORM_PORT}:${TYPEORM_PORT}"
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - backend
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${EXPOSED_CONTAINER_REDIS_PORT}:${REDIS_PORT}"
    networks:
      - backend
networks:
  backend:
    name: backend
    external: true
